// ACTION TYPES
// FAVORITES UI
export const GET_FAVORITES = 'GET_FAVORITES' 
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE' 
// LOCAL
export const GET_LOCAL_FAVORITES = 'GET_LOCAL_FAVORITES' 
export const ADD_LOCAL_FAVORITE = 'ADD_LOCAL_FAVORITE'
export const REMOVE_LOCAL_FAVORITE = 'REMOVE_LOCAL_FAVORITE' 